import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { FluentProvider } from "@fluentui/react-components";
import { BrowserRouter } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import App from "./App";
import { TenantProvider } from "./shell/TenantContext";
import { kpmgLightTheme } from "./theme/kpmg";
const qc = new QueryClient();
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(FluentProvider, { theme: kpmgLightTheme, style: { minHeight: "100vh" }, children: _jsx(QueryClientProvider, { client: qc, children: _jsx(BrowserRouter, { children: _jsx(TenantProvider, { children: _jsx(App, {}) }) }) }) }) }));
